// Mock data for frontend testing (no backend needed)
export const mockUser = {
  id: '1',
  email: 'demo@voiceai.in',
  company_name: 'Demo Company',
  plan: 'free',
}

export const mockCampaigns = [
  {
    id: '1',
    name: 'Bus Driver Reminder — Jan 2025',
    description: 'Daily departure time reminders for all GSRTC bus drivers',
    campaign_type: 'reminder',
    language_priority: 'gu',
    status: 'active',
    total_contacts: 248,
    completed_calls: 186,
    persona_name: 'Priya',
    caller_id: '+917900000001',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'PM Awas Yojana Survey',
    description: 'Verify scheme status and collect beneficiary feedback',
    campaign_type: 'political',
    language_priority: 'gu',
    status: 'completed',
    total_contacts: 520,
    completed_calls: 520,
    persona_name: 'Kavya',
    caller_id: '+917900000002',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'Hospital Appointment Reminder',
    description: 'Remind patients of upcoming appointments',
    campaign_type: 'reminder',
    language_priority: 'hi',
    status: 'paused',
    total_contacts: 85,
    completed_calls: 42,
    persona_name: 'Ananya',
    caller_id: '+917900000003',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'Customer Feedback — Dec',
    description: 'Post-service feedback collection',
    campaign_type: 'survey',
    language_priority: 'en',
    status: 'draft',
    total_contacts: 0,
    completed_calls: 0,
    persona_name: 'Priya',
    caller_id: '',
    created_at: new Date().toISOString(),
  },
]

export const mockStats = {
  completed: '186',
  pending: '42',
  failed: '8',
  scheduled: '12',
  busy: '15',
  no_answer: '9',
  transferred: '3',
}

export const mockCallLogs = [
  {
    id: '1',
    phone: '9876543210',
    variables: { name: 'રાજેશ પટેલ', bus_number: 'Bus 47', departure_time: '6:30 AM' },
    outcome: 'completed',
    language_detected: 'gu',
    duration_sec: 42,
    started_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    transcript: [
      { role: 'assistant', text: 'નમસ્તે રાજેશ ભાઈ! Bus 47 ની departure time 6:30 AM છે. શું confirm કરો છો?', lang: 'gu' },
      { role: 'user', text: 'હા, confirm છે.', lang: 'gu' },
      { role: 'assistant', text: 'ખૂબ સારું! Drive safe. 🙏', lang: 'gu' },
    ],
    collected_data: { confirmed: 'yes' },
  },
  {
    id: '2',
    phone: '9876543211',
    variables: { name: 'Suresh Kumar', bus_number: 'Bus 12', departure_time: '7:00 AM' },
    outcome: 'rescheduled',
    language_detected: 'hi',
    duration_sec: 28,
    started_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    transcript: [
      { role: 'assistant', text: 'नमस्ते Suresh जी! Bus 12 का departure time 7:00 AM है।', lang: 'hi' },
      { role: 'user', text: 'Abhi busy hoon, kal call karo.', lang: 'hi' },
      { role: 'assistant', text: 'ठीक है, कल सुबह call करूंगी। धन्यवाद!', lang: 'hi' },
    ],
    collected_data: { callback_requested: 'tomorrow morning' },
  },
  {
    id: '3',
    phone: '9876543212',
    variables: { name: 'Amit Shah', bus_number: 'Bus 23', departure_time: '8:15 AM' },
    outcome: 'no_answer',
    language_detected: 'gu',
    duration_sec: 0,
    started_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    transcript: [],
    collected_data: {},
  },
  {
    id: '4',
    phone: '9876543213',
    variables: { name: 'Priya Mehta', bus_number: 'Bus 8', departure_time: '9:00 AM' },
    outcome: 'transferred',
    language_detected: 'en',
    duration_sec: 95,
    started_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    transcript: [
      { role: 'assistant', text: 'Hello Priya! Bus 8 departs at 9:00 AM today.', lang: 'en' },
      { role: 'user', text: 'I have a complaint about the route change.', lang: 'en' },
      { role: 'assistant', text: 'I understand. Let me transfer you to our team.', lang: 'en' },
    ],
    collected_data: { complaint: 'route change issue' },
  },
]

